export const currencyByRupee: Currency[] = [
  {
    name: 'DOLLAR',
    value: 0.012271428,
    flag: '🇺🇸',
    symbol: '$',
  },
  {
    name: 'EURO',
    value: 0.01125809,
    flag: '🇪🇺',
    symbol: '€',
  },
  {
    name: 'POUND',
    value: 0.0099194378,
    flag: '🇬🇧',
    symbol: '£',
  },
  {
    name: 'RUBEL',
    value: 0.85040469,
    flag: '🇷🇺',
    symbol: '₽',
  },
  {
    name: 'AUS DOLLAR',
    value: 0.01732574,
    flag: '🇦🇺',
    symbol: 'A$',
  },
  {
    name: 'CAN DOLLAR',
    value: 0.016457908,
    flag: '🇨🇦',
    symbol: 'C$',
  },
  {
    name: 'YEN',
    value: 1.5909089,
    flag: '🇯🇵',
    symbol: '¥',
  },
  {
    name: 'DINAR',
    value: 0.0037446993,
    flag: '🇰🇼',
    symbol: 'KD',
  },
  {
    name: 'BITCOIN',
    value: 0.000000543544886,
    flag: '🎰',
    symbol: '₿',
  },
  {
    name: 'SWISS FRANC',
    value: 0.01049721,
    flag: '🇨🇭',
    symbol: 'CHF',
  },
  {
    name: 'SINGAPORE DOLLAR',
    value: 0.016607,
    flag: '🇸🇬',
    symbol: 'S$',
  },
  {
    name: 'MALAYSIAN RINGGIT',
    value: 0.052072,
    flag: '🇲🇾',
    symbol: 'RM',
  },
  {
    name: 'UAE DIRHAM',
    value: 0.04505,
    flag: '🇦🇪',
    symbol: 'AED',
  },
  {
    name: 'SAUDI RIYAL',
    value: 0.046,
    flag: '🇸🇦',
    symbol: 'SAR',
  },
  {
    name: 'BAHRAINI DINAR',
    value: 0.0047,
    flag: '🇧🇭',
    symbol: 'BHD',
  },
  {
    name: 'KUWAITI DINAR',
    value: 0.0033,
    flag: '🇰🇼',
    symbol: 'KWD',
  },
  {
    name: 'OMANI RIAL',
    value: 0.0047,
    flag: '🇴🇲',
    symbol: 'OMR',
  },
  {
    name: 'QATARI RIYAL',
    value: 0.045,
    flag: '🇶🇦',
    symbol: 'QAR',
  },
  {
    name: 'HONG KONG DOLLAR',
    value: 0.096,
    flag: '🇭🇰',
    symbol: 'HK$',
  },
  {
    name: 'NEW ZEALAND DOLLAR',
    value: 0.0178,
    flag: '🇳🇿',
    symbol: 'NZ$',
  },
  {
    name: 'NORWEGIAN KRONE',
    value: 0.105,
    flag: '🇳🇴',
    symbol: 'NOK',
  },
  {
    name: 'DANISH KRONE',
    value: 0.084,
    flag: '🇩🇰',
    symbol: 'DKK',
  },
  {
    name: 'SWEDISH KRONA',
    value: 0.108,
    flag: '🇸🇪',
    symbol: 'SEK',
  },
  {
    name: 'INDONESIAN RUPIAH',
    value: 177.62,
    flag: '🇮🇩',
    symbol: 'Rp',
  },
  {
    name: 'THAI BAHT',
    value: 0.377,
    flag: '🇹🇭',
    symbol: '฿',
  },
  {
    name: 'SOUTH KOREAN WON',
    value: 14.39,
    flag: '🇰🇷',
    symbol: '₩',
  },
  {
    name: 'PHILIPPINE PESO',
    value: 0.611,
    flag: '🇵🇭',
    symbol: '₱',
  },
  {
    name: 'EGYPTIAN POUND',
    value: 0.193,
    flag: '🇪🇬',
    symbol: 'E£',
  },
  {
    name: 'SOUTH AFRICAN RAND',
    value: 0.191,
    flag: '🇿🇦',
    symbol: 'R',
  },
  {
    name: 'ISRAELI SHEKEL',
    value: 0.044,
    flag: '🇮🇱',
    symbol: '₪',
  },
  {
    name: 'BRAZILIAN REAL',
    value: 0.063,
    flag: '🇧🇷',
    symbol: 'R$',
  },
  {
    name: 'ARGENTINE PESO',
    value: 1.28,
    flag: '🇦🇷',
    symbol: 'AR$',
  },
  {
    name: 'CHILEAN PESO',
    value: 8.67,
    flag: '🇨🇱',
    symbol: 'CLP$',
  },
  {
    name: 'COLOMBIAN PESO',
    value: 48.89,
    flag: '🇨🇴',
    symbol: 'COP$',
  },
  {
    name: 'MEXICAN PESO',
    value: 0.25,
    flag: '🇲🇽',
    symbol: 'MX$',
  },
  {
    name: 'PERUVIAN SOL',
    value: 0.046,
    flag: '🇵🇪',
    symbol: 'S/',
  },
  {
    name: 'VENEZUELAN BOLIVAR',
    value: 2.25,
    flag: '🇻🇪',
    symbol: 'Bs',
  },
  {
    name: 'TURKISH LIRA',
    value: 0.17,
    flag: '🇹🇷',
    symbol: '₺',
  },
  {
    name: 'HUNGARIAN FORINT',
    value: 4.0,
    flag: '🇭🇺',
    symbol: 'Ft',
  },
  {
    name: 'POLISH ZLOTY',
    value: 0.05,
    flag: '🇵🇱',
    symbol: 'zł',
  },
  {
    name: 'CZECH KORUNA',
    value: 0.27,
    flag: '🇨🇿',
    symbol: 'Kč',
  },
  {
    name: 'ROMANIAN LEU',
    value: 0.057,
    flag: '🇷🇴',
    symbol: 'lei',
  },
  {
    name: 'RUSSIAN RUBLE',
    value: 0.85,
    flag: '🇷🇺',
    symbol: '₽',
  },
  {
    name: 'UKRAINIAN HRYVNIA',
    value: 0.33,
    flag: '🇺🇦',
    symbol: '₴',
  },
  {
    name: 'MALDIVIAN RUFIYAA',
    value: 0.18,
    flag: '🇲🇻',
    symbol: 'Rf',
  },
  {
    name: 'SRI LANKAN RUPEE',
    value: 1.38,
    flag: '🇱🇰',
    symbol: 'Rs',
  },
  {
    name: 'NEPALESE RUPEE',
    value: 1.6,
    flag: '🇳🇵',
    symbol: 'Rs',
  },
  {
    name: 'BANGLADESHI TAKA',
    value: 1.15,
    flag: '🇧🇩',
    symbol: '৳',
  },
  {
    name: 'PAKISTANI RUPEE',
    value: 1.75,
    flag: '🇵🇰',
    symbol: 'Rs',
  },
  {
    name: 'AFGHANI',
    value: 1.09,
    flag: '🇦🇫',
    symbol: '؋',
  },
  {
    name: 'IRANIAN RIAL',
    value: 514.0,
    flag: '🇮🇷',
    symbol: '﷼',
  },
  {
    name: 'IRAQI DINAR',
    value: 17.5,
    flag: '🇮🇶',
    symbol: 'IQD',
  },
  {
    name: 'SYRIAN POUND',
    value: 31.5,
    flag: '🇸🇾',
    symbol: '£',
  },
  {
    name: 'LEBANESE POUND',
    value: 18.45,
    flag: '🇱🇧',
    symbol: '£',
  },
  {
    name: 'JORDANIAN DINAR',
    value: 0.0086,
    flag: '🇯🇴',
    symbol: 'JD',
  },
  {
    name: 'MYANMAR KYAT',
    value: 23.54,
    flag: '🇲🇲',
    symbol: 'K',
  },
  {
    name: 'CAMBODIAN RIEL',
    value: 49.0,
    flag: '🇰🇭',
    symbol: '៛',
  },
  {
    name: 'LAO KIP',
    value: 110.5,
    flag: '🇱🇦',
    symbol: '₭',
  },
  {
    name: 'VIETNAMESE DONG',
    value: 285.0,
    flag: '🇻🇳',
    symbol: '₫',
  },
  {
    name: 'MONGOLIAN TUGRIK',
    value: 35.0,
    flag: '🇲🇳',
    symbol: '₮',
  },
  {
    name: 'UZBEKISTANI SOM',
    value: 141.2,
    flag: '🇺🇿',
    symbol: 'сўм',
  },
  {
    name: 'KAZAKHSTANI TENGE',
    value: 5.3,
    flag: '🇰🇿',
    symbol: '₸',
  },
  {
    name: 'KYRGYZSTANI SOM',
    value: 1.05,
    flag: '🇰🇬',
    symbol: 'сом',
  },
  {
    name: 'GEORGIAN LARI',
    value: 0.034,
    flag: '🇬🇪',
    symbol: '₾',
  },
  {
    name: 'ARMENIAN DRAM',
    value: 5.75,
    flag: '🇦🇲',
    symbol: '֏',
  },
];
